language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -r test-requires
script: tox
deploy:
  provider: pypi
  user: core.machinarum
  password:
    secure: KYDAHrOcr8Fp5cmpaJZZREuviX+c9+6DPJlaYQsmL9l1M7PaZHGYXLovT4BrLeemQ5hwF1JXBIx8V6fDzobMxlsXUtvcuBpmF/afoimsOBMj1dkrH9WU+NEhiNQohLur8L6PoJx9FoUmh3m3ng7EaDPhUY/zpVfnA9zwJau1VexN8VzwAF5EQMmkTyo+UYbjmPsvCIFcFtaF9j/ouBu7bkt4hZ1/FJs3lm0ydptWRc7zT45f2NdYhjBvg7E/Ze1MfS67Pnr1uO4HGXo9sZhSUFzh2j9O6+f6D11f2FR2yw6IG6UNO09/XuSQAJCgpxcCYWQFA7Qt+CneE9eupV081ApWnPrYq+FHKYGZhxPedfFh5yVPgnebLF5qflr5OPwLuyvoEsbBcBWR1EpiKVElvyOgXMkHFnB5n3TcuGIxciXeuiOpDiPAUqE+isoOXHZd4qfzjT3NjtIZQZ/M+UT76FMs5/kxpasv8Ywo91fgmGsVhZqLdGOPQcrbXKOkWjyuSveMZAnLYwfzJil6ny4qF9pW/d2DtbNa0sj2AAA9nf12rySZxs0FSBbltxGKiJ6CrZm9ScwRD0h46ebI5dWRtD4xrP4lkTZZ6MmqrxE9scwAeUWy3je3knJ4wU0X61oEm+d2dKS7k1nEDeR07QlqsJ1IFIaxfDIAwAlywg5To/0=
  on:
    tags: true
